# Generated by Django 3.0.4 on 2020-04-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('dateUploaded', models.DateTimeField(verbose_name='Date uploaded')),
            ],
        ),
    ]
