# Generated by Django 3.0.3 on 2020-04-09 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='serial',
            field=models.CharField(default='C12556', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='dateUploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
