# Generated by Django 3.0.3 on 2020-04-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20200408_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default='9BF895', max_length=6, unique=True),
        ),
    ]
