# Generated by Django 3.0.3 on 2020-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_auto_20200410_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='emptyserial',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default='C0E40EA9E21149D5BA38', max_length=20),
        ),
    ]
