# Generated by Django 3.0.3 on 2020-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_auto_20200411_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='doc',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default='D38FB7841BBF46C5B49B', max_length=20),
        ),
    ]
