# Generated by Django 3.0.3 on 2020-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_auto_20200412_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default='2FB6BAC7ADC6421DA704', max_length=20),
        ),
    ]
