# Generated by Django 3.0.3 on 2020-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_auto_20200412_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default='FD88577E67E84F2698C5', max_length=20),
        ),
    ]
