# Generated by Django 3.0.3 on 2020-04-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_auto_20200412_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='code',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default='7110498338172202784861468', max_length=25),
        ),
    ]
