# Generated by Django 3.0.3 on 2020-04-19 05:29

from django.db import migrations, models
import transfer.models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_auto_20200419_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='code',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='file',
            name='serial',
            field=models.CharField(default=transfer.models.serial_gen, editable=False, max_length=26, unique=True),
        ),
    ]
