# Generated by Django 3.0.3 on 2020-04-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0016_auto_20200419_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
